### ISSUE TITLE
Rewrite static URLs with missing trailing slashes

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/static#238]
We used to rewrite static URLs that were missing trailing slashes.
eg.
https://talk.chimpandsee.org/boards -> https://talk.chimpandsee.org/boards/
https://talk.chimpandsee.org/users/MimiA -> https://talk.chimpandsee.org/users/MimiA/

That's stopped working at some point since the move to Azure, leading to broken relative URLs on old Talk pages.
eg. https://talk.chimpandsee.org/users/MimiA links to https://talk.chimpandsee.org/users/comments.html rather than https://talk.chimpandsee.org/users/MimiA/comments.html

Can we restore the rewrite rules for those URLs?

**Comment by eatyourgreens** [comment]
https://github.com/zooniverse/static/pull/181 looks like it might have been relevant to this issue.

**Comment by zwolf** [comment]
My take: 

This isn't the result of a rule that was forgotten, but rather a combination of the ways in which AWS and Azure differ in how they serve files and how the HTML uses relative links. Azure Storage has no concept of folders/directories, and while that's technically true in AWS as well, AWS goes further to emulate the concept when serving files out of S3. This was encountered during the migration [here](https://github.com/zooniverse/pfe-lab/pull/225/files) and [here](https://github.com/zooniverse/anti-slavery-manuscripts/pull/330). S3 responds to relative URLs more in the way that you'd expect by using a 301 Redirect to add the /, while Azure serves the index.html but doesn't make any other changes, leaving `./foo` to mean something different. 

I found this to be true in my own experiments, and here's a blog post talking about it: https://blog.brianbeach.com/posts/2020-01-08-cloud-storage-trailing-slashes/

So as I see it, the fix here is either to change how the relative URLs are built in the HTML (similar to how the above PRs fixed those apps) or to add an nginx rewrite rule to all the talk archives that slaps a `/` on the end of every URL. The latter would also have to take into account files hosted on the same site, since `/file.json` and `/file.json/` aren't the same and the latter doesn't work.

(thanks to @srallen for talking this through with me)

**Comment by eatyourgreens** [comment]
We've still got the scripts to write the HTML from Ouroboros data, so we could run them again. Every resource is also available as JSON, and the HTML can be generated from the JSON files (in theory.) That's a lot of work though.

I looked through C&S, and I think links are broken on every page:
- boards: https://talk.chimpandsee.org/boards
- subjects: https://talk.chimpandsee.org/subjects/ACP000fb8g
- users: https://talk.chimpandsee.org/users/AnLand

Weirdly, links work for tags so I guess I used absolute paths there: https://talk.chimpandsee.org/tags/female

**Comment by eatyourgreens** [comment]
We could change the links here, from relative to absolute paths:
https://github.com/zooniverse/Talk-archiver/blob/987572b4626217314abf45b5c1687f2ee9265e0c/src/subjects/subjects/subject.njk#L38
https://github.com/zooniverse/Talk-archiver/blob/987572b4626217314abf45b5c1687f2ee9265e0c/src/users/users/user.njk#L36
https://github.com/zooniverse/Talk-archiver/blob/987572b4626217314abf45b5c1687f2ee9265e0c/src/users/users/user.njk#L53
https://github.com/zooniverse/Talk-archiver/blob/987572b4626217314abf45b5c1687f2ee9265e0c/src/boards/boards/index.njk#L15
https://github.com/zooniverse/Talk-archiver/blob/987572b4626217314abf45b5c1687f2ee9265e0c/src/boards/boards/index.njk#L26
https://github.com/zooniverse/Talk-archiver/blob/987572b4626217314abf45b5c1687f2ee9265e0c/src/boards/boards/index.njk#L37

Then the problem is: can we rebuild all those HTML pages?

I think rewrite rules might be a faster solution.

**Comment by eatyourgreens** [comment]
Brainstorming potential solutions here: we could generate HTML from the JSON files on demand, using Rails or NextJS.

eg. generate https://talk.chimpandsee.org/users/AnLand from https://talk.chimpandsee.org/api/users/AnLand.json when the HTML is first requested. That first hit would be expensive: that JSON file takes 1.8 minutes to download and parse, for me, in Firefox. However, the content never changes, so we could potentially cache the HTML forever via a CDN.

**Comment by camallen** [comment]
adding a re-write rule is the simplest approach here and avoids the additional work to rebuild the HTML etc. I've done similar things for the talk archive pages to handle the invalid azure file paths `.` mapped to `-` in #181 and #180 

An alternative is to perpetually host this data out of s3 and change the static proxy to use s3 vs azure. However that's probably a last resort.

**Comment by eatyourgreens** [comment]
As a side note, it was interesting to read, via the links above, [how a base URI is established](https://blog.cdivilly.com/2019/02/28/uri-trailing-slashes) for a page.

We could explicitly set the base URI of a page, using [`<base>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base), but I seem to recall we did that in PFE and broke the whole of zooniverse.org?
